[project]
name = "genai-agenticai-by-krish-nayak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain>=0.3.26",
    "langgraph>=0.4.8",
]
